name: Go

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Todo, fix dependencies to be fetched from github artifacts.
      - name: Dependencies
        run: sudo dpkg -i external/*.deb
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: go test -race ./...

  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  goreleaser:
    name: goreleaser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Todo, fix dependencies to be fetched from github artifacts.
      - name: Dependencies
        run: sudo dpkg -i external/*.deb
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: echo "${GITHUB_TOKEN}" | docker login ghcr.io --username $GITHUB_ACTOR --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
